apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rewine-backend-base

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: rewine-backend
  app.kubernetes.io/part-of: rewine
  app.kubernetes.io/managed-by: kustomize

